name: Manual Deploy Metadata

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}   
          ref: gh-pages
          fetch-depth: 0

      - name: Neutralize interactive credential helpers
        shell: powershell
        run: |
          git config --global --unset-all credential.helper 2>$null
          git config --system --unset-all credential.helper 2>$null

      - name: Configure git user
        shell: powershell
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update docs/all_metadata_combined.json from main
        shell: powershell
        run: |
          # Make sure we can read from main
          git fetch origin main

          # Ensure target folder exists on gh-pages
          if (-not (Test-Path "docs")) { New-Item -ItemType Directory -Path "docs" | Out-Null }

          # Write the blob from main to the same path on gh-pages
          git show origin/main:docs/all_metadata_combined.json > docs/all_metadata_combined.json

      - name: Commit & push if changed
        shell: powershell
        run: |
          git add docs/all_metadata_combined.json
          $status = git status --porcelain
          if ($status) {
            git commit -m "Update docs/all_metadata_combined.json on gh-pages"
            git push origin gh-pages
            Write-Host "Changes committed and pushed."
          } else {
            Write-Host "No changes to commit."
          }
