name: Manual Deploy Metadata

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout gh-pages (or create if missing)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          token: ${{ github.token }}
          persist-credentials: false

      - name: Configure git identity (repo-local only)
        shell: powershell
        run: |
          if (-not (Test-Path ".git")) {
            Write-Error "Not a git repository. Did checkout fail?"
          }
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git config --local credential.helper ""

      - name: Get metadata JSON from main
        shell: powershell
        run: |
          git fetch origin main
          # Write file into the root of gh-pages instead of docs/
          git show origin/main:docs/all_metadata_combined.json > all_metadata_combined.json

      - name: Commit if changed
        id: commit
        shell: powershell
        run: |
          git add all_metadata_combined.json
          $status = git status --porcelain
          if ($status) {
            git commit -m "Update all_metadata_combined.json on gh-pages"
            "changed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "changed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "No changes to commit."
          }

      - name: Push to gh-pages
        if: steps.commit.outputs.changed == 'true'
        shell: powershell
        env:
          GIT_AUTH_TOKEN: ${{ github.token }}
          GIT_TERMINAL_PROMPT: "0"
        run: |
          $origin = "https://x-access-token:$env:GIT_AUTH_TOKEN@github.com/${{ github.repository }}.git"
          git remote set-url origin $origin
          git push origin HEAD:gh-pages
          Write-Host "Pushed to gh-pages."
