name: Manual Deploy Metadata

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          persist-credentials: false
          token: ${{ github.token }}

      - name: Neutralize interactive credential helpers
        shell: powershell
        run: |
          git config --global --unset-all credential.helper 2>$null
          git config --system --unset-all credential.helper 2>$null

      - name: Configure git user
        shell: powershell
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update docs/all_metadata_combined.json from main
        shell: powershell
        run: |
          git fetch origin main
          if (-not (Test-Path "docs")) { New-Item -ItemType Directory -Path "docs" | Out-Null }
          git show origin/main:docs/all_metadata_combined.json > docs/all_metadata_combined.json

      - name: Commit if changed
        shell: powershell
        run: |
          git add docs/all_metadata_combined.json
          $status = git status --porcelain
          if ($status) {
            git commit -m "Update docs/all_metadata_combined.json on gh-pages"
          } else {
            Write-Host "No changes to commit."
          }

      - name: Push to gh-pages (explicit auth)
        if: ${{ success() }}
        shell: powershell
        env:
          GIT_AUTH_TOKEN: ${{ github.token }}   
        run: |
          # Set remote to include token so Git never prompts
          $origin = "https://x-access-token:$env:GIT_AUTH_TOKEN@github.com/${{ github.repository }}.git"
          git remote set-url origin $origin

          $ahead = git rev-list --count origin/gh-pages..HEAD 2>$null
          if ($ahead -gt 0) {
            git push origin gh-pages
            Write-Host "Changes pushed."
          } else {
            Write-Host "Nothing to push."
          }
