name: Manual Metadata Update (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  update-index:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run metadata collection script
        run: python .github/scripts/collect_metadata.py

      - name: Commit and push metadata index
        shell: powershell
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/metadata_index.json

          if (-not (git diff --cached --quiet)) {
            git commit -m "Metadata index auto-update via self-hosted runner"

            git remote set-url origin "https://x-access-token:$env:GH_PUSH_TOKEN@github.com/Insidethemind/Node-Society.git"
            git push origin main
          } else {
            Write-Host "No changes to commit."
          }
