name: Manual Metadata Update (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  update-index:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run metadata collection script
        run: python .github/scripts/collect_metadata.py

      - name: Commit and push metadata index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metadata_index.json
          git diff --cached --quiet || git commit -m "Manual metadata index update via self-hosted runner"
          git push
