name: Manual Metadata Update (Python)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  combine:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }} 
          fetch-depth: 0

      - name: Run Python Script to Combine Metadata
        shell: pwsh
        run: python .github/scripts/collect_metadata.py

      - name: Commit and Push Combined Metadata JSON
        shell: pwsh
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/all_metadata_combined.json

          $status = git status --porcelain
          if ($status) {
            git commit -m "Update combined metadata JSON"
            git push
          } else {
            Write-Output "No changes to commit"
          }
